# This data file was generated by the Spreadsheet Calculator.  That is SC-IM, the improved one!
# You almost certainly shouldn't edit it.

leftstring B0 = "January"
leftstring C0 = "February"
leftstring D0 = "March"
leftstring A1 = "Unit 1"
let B1 = 23.45
let C1 = 10.13
let D1 = 8.456
leftstring A2 = "Unit 2"
let B2 = 18.22
let C2 = 45
let D2 = 11.78
leftstring A3 = "Unit 3"
let B3 = 4.567
let C3 = 30.41
let D3 = 19.22
leftstring A4 = "Total"
let B4 = @sum(B1:B3)
let C4 = @sum(C1:C3)
let D4 = @sum(D1:D3)
leftstring B6 = "Јануар"
leftstring C6 = "Фебруар"
leftstring D6 = "Март"
leftstring A7 = "Артикал 1"
let B7 = 45000
let C7 = 5000
let D7 = 64300
leftstring A8 = "Артикал 2"
let B8 = 12000
let C8 = 21500
let D8 = 9800
leftstring A9 = "Артикал 3"
let B9 = 16000
let C9 = 13000
let D9 = 11430
leftstring A10 = "Просек"
let B10 = @avg(B7:B9)
let C10 = @avg(C7:C9)
let D10 = @avg(D7:D9)
goto A10
