# This data file was generated by the Spreadsheet Calculator.  That is SC-IM, the improved one!
# You almost certainly shouldn't edit it.

leftstring B0 = "January"
leftstring C0 = "February"
leftstring D0 = "March"
leftstring A1 = "Unit 1"
let B1 = 23.45
let C1 = 10.13
let D1 = 8.456
leftstring A2 = "Unit 2"
let B2 = 18.22
let C2 = 45
let D2 = 11.78
leftstring A3 = "Unit 3"
let B3 = 4.567
let C3 = 30.41
let D3 = 19.22
leftstring A4 = "Total"
let B4 = @sum(B1:B3)
let C4 = @sum(C1:C3)
let D4 = @sum(D1:D3)
goto D4
