'\" t
.\" Manpage for table(1)
.
.mso an-ext.tmac
.
.TH TABLE "1" "27 Oct 2020" "table v0.1.2-beta" "General Commands Manual"
.SH NAME
table \- Command line utility to format and display CSV.
.
.SH SYNOPSIS
.SY table
.RI [ options ]
.RI [ filename ]
.YS
.
.SH COPYRIGHT
table Copyright \(co 2020 Strahinya Radich.
.
.SH DESCRIPTION
.B Table 
is a command line utility to format and display 
.SM CSV.
It parses the given file or standard input as 
.SM CSV
and prints out a table using Unicode characters for box
drawing.
.
.SH OPTIONS
.
.TP
.B \-a
.TQ
.B \-\-ansi
.br
.SM ANSI SGR
processing in the input: add
.EX
.in +4
\\e[0m\\e[?25h
.in -4
.EE
to the end of each cell. (Also see
.SM
.B "BUGS "
below.)
.
.TP
.B \-b
.TQ
.B \-\-border-mode
.br
Border mode: force single column.
.
.TP
.BR \-c " <\fIcols\fR>"
.TQ
.BR \-\-columns= <\fIcols\fR>
.br
Set maximum table width in columns (default 80).
.
.TP
.BR \-d " <\fIdelim\fR>"
.TQ
.BR \-\-delimiter= <\fIdelim\fR>
.br
Set field delimiter (default ","). First line of the input determines the number
of table columns. Special characters, like ";", need to be quoted:
.EX
.in +4
$ table -d ';'
.in -4
.EE
.
.TP
.BR \-h
.TQ
.B \-\-help
.br
Print this usage information screen.
.
.TP
.BR \-s " <\fIset\fR>"
.TQ
.BR \-\-symbols= <\fIset\fR>
.br
Use table symbol set <\fIset\fR> for table lines, where <\fIset\fR> is one of
the following (format: <\fIborder\fR><\fIinner border\fR>):
.TS
box tab(@);
c l.
\fIaa\fR@ascii-ascii,
_
\fIss\fR@single-single,
_
\fIsd\fR@single-double,
_
\fIds\fR@double-single (default),
_
\fIdd\fR@double-double.
.TE
.
.TP
.B \-v
.TQ
.B \-\-version
.br
Print program version and exit.
.
.SH "SEE ALSO"
.BR awk (1),
.BR sed (1)
.
.SH EXAMPLES
.
.TP
.EX
$ watch "table /proc/loadavg -d ' ' -c 50 -s ss"
.EE
Periodically display 
.SM CPU 
load information in a single-line table
.
.TP
.EX
$ ls -l | tail -n +2 | sed -e 's/ \+/ /g' | table -d ' '
.EE
Format a long list of files in the current directory in a double line table with
single-line column divisors
.
.TP
.EX
$ ls -l | tail -n +2 | awk '{ print $1 " " $9 }' | table -d ' ' -c 30
.EE
Like the above, but only permissions and file names are printed in a narrow
table
.
.SH BUGS
.
.PP
.SM ANSI
sequences are not handled as well as they should as of 
.B table
v0.1.2 and the code to format them will likely be rewritten. They are displayed
to an extent, together with the codes to reset the formatting, but the line and
column lengths are still not correctly determined.
.
.PP
For more details, see the
.SM TODO
file in the repository.
.
.PP
Bugs can be reported using the Github issue tracker at:
.UR https://\:github.com/\:Strahinja/\:table/\:issues
.UE

